nome = "Juninho Dev"

print(nome.capitalize())("Juninho Dev")
print(nome.casefold())("Juninho Dev")
print(nome.count("r"))(1)
print(nome.find("Dev"))(9)
print(nome.index("Juninho"))(0)
print(nome.isalnum())("False")
print(nome.isalpha())("False")
print(nome.isascii())("True")
print(nome.isdecimal())("False")
print(nome.isdigit())("False")
print(nome.isidentifier())("False")
print(nome.islower())("False")
print(nome.isupper())("False")
print(nome.isnumeric())("False")
print(nome.isprintable())("True")
